var mobilePrice = 20000;
var laptopPrice = 40000;
var addition = mobilePrice + laptopPrice;
var substraction = laptopPrice - mobilePrice;
var multiplication = mobilePrice * laptopPrice;
var division = laptopPrice / mobilePrice;
console.log(addition);
console.log(substraction);
console.log(multiplication);
console.log(division);